### ISSUE TITLE
Question about triplane visualization.

### ISSUE THREAD

**Issue by pansanity666** [Lakonik/SSDNeRF#10]
Hi Hansheng,

How did you get the triplane visualization shown in the paper? 

Best,

**Comment by Lakonik** [comment]
Hi! The visualizations will be automatically saved in `work_dirs/<cfg name>/viz_*` if you run the training or testing script. Alternatively, you can also use the `save code` button in SSDNeRF GUI to visualize the triplanes.

**Comment by pansanity666** [comment]
> Hi! The visualizations will be automatically saved in `work_dirs/<cfg name>/viz_*` if you run the training or testing script. Alternatively, you can also use the `save code` button in SSDNeRF GUI to visualize the triplanes.

Thanks, I will try it!
