### ISSUE TITLE
different iteration numbers in unconditional generation and reconstruction

### ISSUE THREAD

**Issue by byran-wang** [Lakonik/SSDNeRF#12]
@Lakonik Thank you for your great SSDNeRF work.

And I have one confusion with your work: Why the iteration number is 1M in unconditional generation training, which is significantly larger than 80K in reconstruction training.

**Comment by Lakonik** [comment]
Hi! Thank you for your interest in our work.

As mentioned in the paper, longer training schedule on a small dataset like ShapeNet Cars would cause the model to overfit training samples. Our temporary workaround is to use early stopping (at 80K) for a tradeoff between quality and generalization in reconstruction training.

**Comment by byran-wang** [comment]
Thanks for your kind answer.
