### ISSUE TITLE
[Errno 2] No such file or directory: 'data/shapenet/cars_test/1a3782ae4bd711b66b418c7d9fedcaa9/rgb'

### ISSUE THREAD

**Issue by colian** [Lakonik/SSDNeRF#15]
Hi, thanks for your work.

When I try to run "python train.py configs/supp_cfgs/ssdnerf_cars_reconskitti.py".
It turns out "[Errno 2] No such file or directory: 'data/shapenet/cars_test/1a3782ae4bd711b66b418c7d9fedcaa9/rgb'".
After I check the config file, it seems like I have no "test_pose_override", "cars_train" and "cars_test" files. (Only have cars_kitti)
How can i get these files?

Look forward your reply, thanks.

**Comment by Lakonik** [comment]
Hi! The kitti dataset is not for training. You can run the test script with the shapnet-pretrained model: https://drive.google.com/file/d/1hsnUW7dZ45aPqXxtOVrOSBl1gQA_8wH-/view?usp=drive_link

**Comment by colian** [comment]
Thanks for your help, but my display page is blank (No errors come out) after running the visualization code, do u know why?

**Comment by Lakonik** [comment]
Please run the testing script:
```
python test.py configs/supp_cfgs/ssdnerf_cars_reconskitti.py checkpoint/ssdnerf_cars_recons1v_80k_emaonly.pth --gpu-ids 0 1
```
Then the visualized results will be automatically saved into `work_dirs`.

**Comment by colian** [comment]
Hi, thanks. I follow your suggestion to run the code. It also turns out "[Errno 2] No such file or directory: 'data/shapenet/cars_test/1a3782ae4bd711b66b418c7d9fedcaa9/rgb'".
And i checked the config file "ssdnerf_cars_reconskitti.py", it indeed needs this file?

**Comment by colian** [comment]
Do u mean using the same 1a3782ae4bd711b66b418c7d9fedcaa9 file by downloading shapenet?

**Comment by Lakonik** [comment]
> Hi, thanks. I follow your suggestion to run the code. It also turns out "[Errno 2] No such file or directory: 'data/shapenet/cars_test/1a3782ae4bd711b66b418c7d9fedcaa9/rgb'". And i checked the config file "ssdnerf_cars_reconskitti.py", it indeed needs this file?

This dependency should not be necessary. I have fixed it now. Thanks for the feedback!

**Comment by Lakonik** [comment]
> Thanks for your fast reply, but now it shows "[Errno 2] No such file or directory: 'demo/camera_spiral_cars/rgb’". =,=. Do u mean we should set 'test_pose_override=None'?

Can you post the full error msg?

**Comment by colian** [comment]
The running code is 'python [test.py](http://test.py/) configs/supp_cfgs/ssdnerf_cars_reconskitti.py checkpoint/ssdnerf_cars_recons1v_80k_emaonly.pth --gpu-ids 0'

Results->
Traceback (most recent call last):
File "/xxx/anaconda3/envs/ssdnerf/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
return obj_cls(**args)
File "/xxx/SSDNeRF/lib/datasets/shapenet_srn.py", line 74, in **init**
image_names = os.listdir(image_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'demo/camera_spiral_cars/rgb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "[[test.py](http://test.py/)](http://[test.py](http://test.py/)/)", line 75, in <module>
main()
File "[test.py](http://test.py/)", line 58, in main
tools.test.main()
File "/xxx/SSDNeRF/tools/test.py", line 212, in main
dataset = build_dataset(cfg.data[eval_cfg.data])
File "/xxx/mmgeneration/mmgen/datasets/builder.py", line 60, in build_dataset
dataset = build_from_cfg(cfg, DATASETS, default_args)
File "/xxx/anaconda3/envs/ssdnerf/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
raise type(e)(f'{obj_cls.**name**}: {e}')
FileNotFoundError: ShapeNetSRN: [Errno 2] No such file or directory: 'demo/camera_spiral_cars/rgb'

**Comment by Lakonik** [comment]
> The running code is 'python [test.py](http://test.py/) configs/supp_cfgs/ssdnerf_cars_reconskitti.py checkpoint/ssdnerf_cars_recons1v_80k_emaonly.pth --gpu-ids 0'
> 
> Results-> Traceback (most recent call last): File "/xxx/anaconda3/envs/ssdnerf/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg return obj_cls(**args) File "/xxx/SSDNeRF/lib/datasets/shapenet_srn.py", line 74, in **init** image_names = os.listdir(image_dir) FileNotFoundError: [Errno 2] No such file or directory: 'demo/camera_spiral_cars/rgb'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "[[test.py](http://test.py/)](http://[test.py](http://test.py/)/)", line 75, in main() File "[test.py](http://test.py/)", line 58, in main tools.test.main() File "/xxx/SSDNeRF/tools/test.py", line 212, in main dataset = build_dataset(cfg.data[eval_cfg.data]) File "/xxx/mmgeneration/mmgen/datasets/builder.py", line 60, in build_dataset dataset = build_from_cfg(cfg, DATASETS, default_args) File "/xxx/anaconda3/envs/ssdnerf/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') FileNotFoundError: ShapeNetSRN: [Errno 2] No such file or directory: 'demo/camera_spiral_cars/rgb'

It seems that you may have not checked out the latest commit.

**Comment by colian** [comment]
I missed the changed file in lib, now solved it, thank u very much.
