### ISSUE TITLE
Code releasing.

### ISSUE THREAD

**Issue by junshengzhou** [Lakonik/SSDNeRF#2]
Hi, 
Thanks for sharing your great job! I would like to know when will you release the code? Couldn't wait to have a try.
Best,

**Comment by Lakonik** [comment]
Thank you for your interest in our work! The project code will be released this summer. In the released version we will possibly add some extended modules beyond the scope of the current paper, so stay tuned :)

**Comment by junshengzhou** [comment]
I see. Thanks for your reply!

**Comment by yifanjiang19** [comment]
looking forward to the code release too!

**Comment by slothfulxtx** [comment]
Looking forward to the code release too! Couldn't wait to have a try.
