### ISSUE TITLE
Question about the data needed for single-view recon testing

### ISSUE THREAD

**Issue by TLB-MISS** [Lakonik/SSDNeRF#28]
First of all, thank you so much for sharing your great work!

I have a question about the types of data needed for single-view reconstruction.
In the paper, it appears that 3D can be reconstructed with just a single view image.
However, in the code, poses and intrinsics are also needed. Also, the chairs_test_cache.pkl file seems to be needed for chair reconstruction. Are poses and intrinsics also necessary for single view reconstruction test? And what does the pickle file do?
Lastly, I would really appreciate it if you could tell me what steps must be taken to test single view reconstruction from an arbitrary real (chair) image.

Thanks

**Comment by Lakonik** [comment]
Hi! In the paper we mentioned that camera parameters are currently required to perform image-based reconstruction. To perform reconstruction from real images, you may either use a pose estimator or manually set the camera in GUI (this feature may be streamlined in a future update of this codebase). Many of our tests indicate that SSDNeRF is reasonably robust to pose errors.

The cache file is auto generated from the dataset, and is therefore not necessary (you can comment out that line).

**Comment by TLB-MISS** [comment]
@Lakonik 

Thank you for answer!
I didn't read the paper carefully... I'm sorry.

**Comment by TLB-MISS** [comment]
@Lakonik 

I have additional questions!
I found out that the camera pose is in opencv format. But is the format w2c form or c2w form?

**Comment by Lakonik** [comment]
The pose matrix is c2w, from opencv's camera coordinate system to the world.
