### ISSUE TITLE
Test PSNR not improving on custom dataset

### ISSUE THREAD

**Issue by xiyichen** [Lakonik/SSDNeRF#32]
Nice work! I'm trying to train a custom face dataset (FaceScape) using the one-view reconstruction setting. Since the cameras in this dataset is already in OpenCV format, there's no conversion needed. I have tuned the radius parameter to reflect the change in the object size. However, the test PSNR never improves, although training PSNR does.
<img width="789" alt="Screenshot 2023-11-21 at 19 59 10" src="https://github.com/Lakonik/SSDNeRF/assets/50854238/a093b4c4-e56f-43a3-b435-e73e0328e0b4">
![scene_122_01_000018_psnr7 6_ssim0 24_lpips0 726](https://github.com/Lakonik/SSDNeRF/assets/50854238/5f102526-656d-4090-a814-55dd70d45bf9)
![scene_122_01_000010_psnr9 0_ssim0 30_lpips0 711](https://github.com/Lakonik/SSDNeRF/assets/50854238/1d6e9f34-d784-4df0-a261-31c162f4425f)
![scene_122_01_000004_psnr8 3_ssim0 29_lpips0 723](https://github.com/Lakonik/SSDNeRF/assets/50854238/378af3e1-2a99-448c-bc1b-ac54d93d0ddb)
It also seems the rendered faces are not correctly localized. However I double checked the camera parameters, and made sure they are in the same convention as SRN car dataset and the poses loaded are c2w matrices. The only difference is that the intrinsics for each camera are different, but I've modified the dataloader correspondingly.

I'm a bit lost on what could be wrong. Do you make other assumptions on the camera parameters? Are there any other parameters that I should tune?

**Comment by Lakonik** [comment]
Thank you for your interest in our work!

How is the training PSNR actually? The screenshot only shows very early results so it's hard to tell if anything goes wrong. Evaluating the model at this early stage is not really helpful.

If the image resolution has been changed, then you probably need to tweak some parameters like guidance scale. But if it's just the camera intrinsics then it should be ok. Also starting from the SRN car config for face reconstruction is a good choice.

**Comment by xiyichen** [comment]
Thank you for your fast response! It turned out it was indeed just too early in the training stage. After training overnight, now the evaluation results look reasonable.
