### ISSUE TITLE
A naive question about Table 1. 

### ISSUE THREAD

**Issue by pansanity666** [Lakonik/SSDNeRF#4]
Hi, 
     I have a naive question about Tab. 1 in the paper. Does ``A+-B`` represent ``mean+-std``, which means you run the experiments for multiple times and report the mean and std value? 

Best,

**Comment by Lakonik** [comment]
Thank you for your interest in our work! In `A+-B`, `B` is actually `2*std` which is the 95% confidence interval. This was calculated using multiple testing runs of the same trained model.

**Comment by pansanity666** [comment]
> Thank you for your interest in our work! In `A+-B`, `B` is actually `2*std` which is the 95% confidence interval. This was calculated using multiple testing runs of the same trained model.

Thanks for reply. So, is it a common practice that mean+-2*std represents 95% confidence interval? (I am not familiar with machine learning, and it seems not commonly used in deep learning papers.)

Best,

**Comment by pansanity666** [comment]
That will be nice!
