### ISSUE TITLE
No such file: 'abotables_inception_stylegan.pkl'

### ISSUE THREAD

**Issue by jiangzt** [Lakonik/SSDNeRF#5]
Thank you for your great work! It reports an error: 'No such file: 'abotables_inception_stylegan.pkl''. How can I obtain 'abotables_inception_stylegan.pkl'.

**Comment by colian** [comment]
Hi, how u solved this issue? Have I missed sth? =.=

**Comment by jiangzt** [comment]
yes, i have solved it



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 7, 2023 14:20 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Lakonik/SSDNeRF] No such file:'abotables_inception_stylegan.pkl' (Issue #5)




 
Hi, how u solved this issue? Have I missed sth? =.=
